name: threat_env
dependencies:
  - python=3.10
  - pip
  - pip:
      - aiohappyeyeballs @ file:///home/conda/feedstock_root/build_artifacts/aiohappyeyeballs_1733331917983/work
      - aiohttp @ file:///D:/bld/aiohttp_1734596894871/work
      - aiosignal @ file:///home/conda/feedstock_root/build_artifacts/aiosignal_1734342155601/work
      - annotated-types @ file:///home/conda/feedstock_root/build_artifacts/annotated-types_1733247046149/work
      - anyio @ file:///home/conda/feedstock_root/build_artifacts/anyio_1736174388474/work
      - attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1737819173731/work
      - Brotli @ file:///D:/bld/brotli-split_1687884251065/work
      - certifi @ file:///home/conda/feedstock_root/build_artifacts/certifi_1734380492396/work/certifi
      - cffi @ file:///D:/bld/cffi_1725560706917/work
      - charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1735929714516/work
      - colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1733218098505/work
      - contourpy==1.3.2
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - datasets @ file:///home/conda/feedstock_root/build_artifacts/datasets_1733931864043/work
      - dill @ file:///home/conda/feedstock_root/build_artifacts/dill_1706434688412/work
      - distro @ file:///home/conda/feedstock_root/build_artifacts/distro_1734729835256/work
      - exceptiongroup @ file:///home/conda/feedstock_root/build_artifacts/exceptiongroup_1733208806608/work
      - filelock @ file:///home/conda/feedstock_root/build_artifacts/filelock_1737517818712/work
      - fonttools==4.58.1
      - frozenlist @ file:///D:/bld/frozenlist_1737645258591/work
      - fsspec @ file:///home/conda/feedstock_root/build_artifacts/fsspec_1725543257300/work
      - fuzzywuzzy==0.18.0
      - greenlet==3.1.1
      - h11 @ file:///home/conda/feedstock_root/build_artifacts/h11_1733327467879/work
      - h2 @ file:///home/conda/feedstock_root/build_artifacts/h2_1733298745555/work
      - hpack @ file:///home/conda/feedstock_root/build_artifacts/hpack_1737618293087/work
      - httpcore @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_httpcore_1731707562/work
      - httpx @ file:///home/conda/feedstock_root/build_artifacts/httpx_1733663348460/work
      - httpx-sse==0.4.0
      - huggingface_hub @ file:///home/conda/feedstock_root/build_artifacts/huggingface_hub_1736350098712/work
      - hyperframe @ file:///home/conda/feedstock_root/build_artifacts/hyperframe_1737618333194/work
      - idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1733211830134/work
      - Jinja2==3.1.5
      - jiter @ file:///D:/bld/jiter_1734065511739/work
      - joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1733736026804/work
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.8
      - langchain==0.3.17
      - langchain-community==0.3.16
      - langchain-core==0.3.33
      - langchain-text-splitters==0.3.5
      - langsmith==0.3.3
      - Levenshtein==0.26.1
      - MarkupSafe==3.0.2
      - marshmallow==3.26.0
      - matplotlib==3.10.3
      - mpmath==1.3.0
      - multidict @ file:///D:/bld/multidict_1729065636540/work
      - multiprocess @ file:///D:/bld/multiprocess_1724954693267/work
      - mypy-extensions==1.0.0
      - networkx==3.4.2
      - numpy==1.26.4
      - ollama==0.4.7
      - openai==0.28.0
      - orjson==3.10.15
      - packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1733203243479/work
      - pandas @ file:///D:/bld/pandas_1726878554493/work
      - pillow==11.1.0
      - propcache @ file:///D:/bld/propcache_1737635564183/work
      - pyarrow @ file:///C:/b/abs_0aneze9pgl/croot/pyarrow_1738229440651/work/python
      - pycparser @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_pycparser_1733195786/work
      - pydantic @ file:///home/conda/feedstock_root/build_artifacts/pydantic_1737761369378/work
      - pydantic-settings==2.7.1
      - pydantic_core @ file:///D:/bld/pydantic-core_1734571360609/work
      - pyparsing==3.2.3
      - PySocks @ file:///D:/bld/pysocks_1733217287171/work
      - python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1733215673016/work
      - python-docx==1.1.2
      - python-dotenv==1.0.1
      - python-Levenshtein==0.26.1
      - pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1706886791323/work
      - PyYAML @ file:///D:/bld/pyyaml_1737454660454/work
      - RapidFuzz==3.12.1
      - regex @ file:///D:/bld/regex_1730952204165/work
      - requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1733217035951/work
      - requests-toolbelt==1.0.0
      - safetensors @ file:///D:/bld/safetensors_1736382957946/work
      - scikit-learn @ file:///D:/bld/scikit-learn_1736496780928/work/dist/scikit_learn-1.6.1-cp311-cp311-win_amd64.whl#sha256=b8f37c282c66c737a09228918d0bfcadafb9f1d4bfb1dc6289040870d453703b
      - scipy @ file:///C:/bld/scipy-split_1736617341862/work/dist/scipy-1.15.1-cp311-cp311-win_amd64.whl#sha256=b108af0a36e273abc043e494d924d0c5598b28bbd5aca689ad9db38336e78f16
      - seaborn==0.13.2
      - sentence-transformers==3.4.1
      - six @ file:///home/conda/feedstock_root/build_artifacts/six_1733380938961/work
      - sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1733244044561/work
      - SQLAlchemy==2.0.37
      - sympy==1.13.3
      - tenacity @ file:///home/conda/feedstock_root/build_artifacts/tenacity_1733649050774/work
      - tenseal==0.3.16
      - threadpoolctl @ file:///home/conda/feedstock_root/build_artifacts/threadpoolctl_1714400101435/work
      - tokenizers @ file:///D:/bld/tokenizers_1732733984122/work/bindings/python
      - torch==2.7.0+cu118
      - torchaudio==2.7.0+cu118
      - torchvision==0.22.0+cu118
      - tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1735661334605/work
      - transformers @ file:///home/conda/feedstock_root/build_artifacts/transformers_1737429274610/work
      - trustllm @ file:///home/conda/feedstock_root/build_artifacts/trustllm_1705177247215/work
      - typing-inspect==0.9.0
      - typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1733188668063/work
      - tzdata @ file:///home/conda/feedstock_root/build_artifacts/python-tzdata_1737541069190/work
      - urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1734859416348/work
      - win_inet_pton @ file:///D:/bld/win_inet_pton_1733130564612/work
      - xxhash @ file:///D:/bld/python-xxhash_1725272140818/work
      - yarl @ file:///D:/bld/yarl_1737575828275/work
      - zstandard==0.23.0
